// src/lib/mastodon-instances.ts

// A curated list of popular Mastodon instances for the search feature.
export const mastodonInstances = [
  'pawoo.net',
  'mastodon.social',
  'dev.brighteon.social',
  'piaille.fr',
  'universeodon.com',
  'mastodon.world',
  'gunbark.dev',
  'mstdn.jp',
  'mastodon.cloud',
  'm.cmx.im',
  'mstdn.party',
  'good.news',
  'techhub.social',
  'kolektiva.social',
  'pixelfed.de',
  'ohai.social',
  'mas.to',
  'pravda.me',
  'troet.cafe',
  'mastodon.uno',
  'social.vivaldi.net',
  'aethy.com',
  'c.im',
  'mastodon.nl',
  'mstdn.social',
  'mastodonapp.uk',
  'infosec.exchange',
  'loforo.com',
  'mastodon.sdf.org',
  'thoughtpunks.com',
  'brighteon.social',
  'pixelfed.social',
];